import { StyleSheet } from "react-native";

export const WelcomeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f6f8ff",
  },
  content: {
    padding: 24,
    paddingBottom: 40,
  },
  glowTop: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 160,
    backgroundColor: "rgba(59, 130, 246, 0.2)",
    top: -120,
    left: -60,
  },
  glowBottom: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 150,
    backgroundColor: "rgba(16, 185, 129, 0.18)",
    bottom: -120,
    right: -80,
  },
  brand: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1e3a8a",
    textAlign: "center",
    letterSpacing: 1.2,
  },
  subtitle: {
    fontSize: 16,
    color: "#475569",
    textAlign: "center",
    marginTop: 6,
  },
  heroCard: {
    marginTop: 24,
    padding: 20,
    borderRadius: 24,
    backgroundColor: "#ffffff",
    shadowColor: "#1f2937",
    shadowOpacity: 0.12,
    shadowRadius: 18,
    elevation: 6,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#0f172a",
    textAlign: "center",
  },
  heroText: {
    textAlign: "center",
    color: "#64748b",
    marginTop: 8,
    marginBottom: 16,
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  priceCard: {
    flex: 1,
    padding: 14,
    marginHorizontal: 6,
    borderRadius: 16,
    backgroundColor: "#eff6ff",
    alignItems: "center",
  },
  priceLabel: {
    fontSize: 13,
    color: "#1d4ed8",
    fontWeight: "600",
  },
  priceValue: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1e3a8a",
    marginTop: 6,
  },
  priceUnit: {
    fontSize: 12,
    color: "#64748b",
  },
  offerBanner: {
    marginTop: 20,
    padding: 18,
    borderRadius: 18,
    backgroundColor: "#ef4444",
    alignItems: "center",
  },
  offerTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#fff",
  },
  offerText: {
    fontSize: 14,
    color: "#fee2e2",
    marginTop: 6,
  },
  offerNote: {
    fontSize: 12,
    color: "#fff",
    marginTop: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  serviceCard: {
    marginTop: 22,
    padding: 18,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    shadowColor: "#1f2937",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 12,
  },
  bulletItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  bulletDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#22c55e",
    marginTop: 6,
    marginRight: 10,
  },
  bulletText: {
    flex: 1,
    color: "#475569",
    fontSize: 14,
    lineHeight: 20,
  },
  ctaCard: {
    marginTop: 22,
    padding: 20,
    borderRadius: 20,
    backgroundColor: "#0f172a",
  },
  ctaTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
  },
  ctaSubtitle: {
    marginTop: 6,
    color: "#cbd5f5",
    marginBottom: 16,
  },
  whatsappButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#22c55e",
    paddingVertical: 12,
    borderRadius: 30,
  },
  whatsappIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.25)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  whatsappIconText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "700",
  },
  whatsappText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 15,
  },
  contactTitle: {
    marginTop: 22,
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
    textAlign: "center",
  },
  contactText: {
    textAlign: "center",
    color: "#475569",
    marginTop: 4,
  },
});
